spring:
  config:
    import:
      - "optional:nacos:${spring.application.name}.yml"
      - "optional:nacos:common.yml"
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 47.109.137.128:8848
        namespace: dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
